name: Gradle Build

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        jdk: [ 8, 11, 17, 20 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.jdk }}
      - uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew build "-Pme.champeau.japicmp.javaToolchain.test=${{ matrix.jdk }}"
