name: Main

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        # Test on all LTS JDKs and the latest JDK.
        jdk: [ 8, 11, 17, 21, 24 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.jdk }}
      - uses: gradle/actions/setup-gradle@v5
      - name: Build
        run: ./gradlew build "-Pme.champeau.japicmp.javaToolchain.test=${{ matrix.jdk }}"
